function [data, coVarNames] = generateDataForCsv(DATA, EEG, ...
                                                 indbadepoch, su, sep)

    % Calculate all the time-independent variables
    suj_id      = repmat(su, size(EEG.data,3), 1);
    palnum      = [DATA.palnum]';
    tipo        = [DATA.tipo]'; 
    pred        = [DATA.pred]';
    freq        = [DATA.freq]';
    lngth       = [DATA.length]';
    MaxJump     = [DATA.MJ]';
    bad_epoch   = ~indbadepoch';
    stopword    = ~ismember([DATA.catsimple],'anv')';

    n_orac = []; pal = [];
    for io = 1:length(DATA)
        n_orac  = [n_orac; repmat(DATA(io).ind, max(DATA(io).palnum), 1)];
        pal     = [pal {DATA(io).palabras{:}}];
    end

    data = {num2str(suj_id) ...
            num2str(palnum)...     
            num2str(tipo)...       
            num2str(pred)...       
            num2str(freq)...       
            num2str(lngth)...      
            num2str(MaxJump)...    
            num2str(bad_epoch)...  
            num2str(stopword)... 
            num2str(n_orac)...
            char(pal)...
            };

    coVarNames = [ 'suj_id'    sep ...
                        'palnum'    sep ...     
                        'tipo'      sep ...       
                        'pred'      sep ...       
                        'freq'      sep ...       
                        'lngth'     sep ...      
                        'MaxJump'   sep ...    
                        'bad_epoch' sep ...  
                        'stopword'  sep ... 
                        'n_orac'    sep ...
                        'pal'       ];

end
